name: E2E Testing
on: [push]

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1
    strategy:
      matrix:
        node-version: [14.x]
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
    steps:
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.2
      - name: Install deps
        run: pnpm install
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Build Project for Testing
        run: pnpm build
      - name: Run Playwright
        run: pnpm test:e2e
